# Generated by Django 4.2.9 on 2024-01-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loginlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=50)),
                ('ip', models.CharField(default=None, max_length=50)),
                ('login_time', models.DateTimeField(default=None)),
            ],
            options={
                'verbose_name': '登录日志',
                'db_table': 'loginlog',
            },
        ),
    ]
